### ISSUE TITLE
Update to PyMySQL==1.0.3

### ISSUE THREAD

**Issue by tylerm007** [ApiLogicServer/ApiLogicServer-src#1]
Can we update the version of pymysql?

**Comment by valhuber** [comment]
sure...

1. Don't forget setup.py
2. And the tests

**Comment by valhuber** [comment]
Done

**Comment by tylerm007** [comment]
Build and Test



>>
Exception has occurred: ValueError (note: full exception trace is shown but
execution is paused at: _run_module_as_main)

   -

Traceback detected
File "
/Users/tylerband/dev/ApiLogicServer/ApiLogicServer-dev/org_git/ApiLogicServer-src/tests/build_and_test/build_and_test.py",
line 164, in check_command raise ValueError("Traceback detected") File "
/Users/tylerband/dev/ApiLogicServer/ApiLogicServer-dev/org_git/ApiLogicServer-src/tests/build_and_test/build_and_test.py",
line 183, in run_command check_command(result) File "
/Users/tylerband/dev/ApiLogicServer/ApiLogicServer-dev/org_git/ApiLogicServer-src/tests/build_and_test/build_and_test.py",
line 410, in docker_creation_tests build_container = run_command(build_cmd,
^^^^^^^^^^^^^^^^^^^^^^ File "
/Users/tylerband/dev/ApiLogicServer/ApiLogicServer-dev/org_git/ApiLogicServer-src/tests/build_and_test/build_and_test.py",
line 828, in <module> docker_creation_tests(api_logic_server_tests_path)
File "
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py",
line 88, in _run_code exec(code, run_globals) File "
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py",
line 198, in _run_module_as_main (Current frame) return _run_code(code,
main_globals, None, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError:
Traceback detected
